### ISSUE TITLE
Termina el ejercicio

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-VictoriaDiro#1]
Buen trabajo @VictoriaDiro !

Algunas pistas para acabarlo:

- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: los tipos tienen que ser una lista, no pueden ser un h3, recuerda que son elementos relacionados. Un OL o UL es lo suyo.
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Organiza los estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props: falta el de los tipos
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usary sus referencias

Si tienes cualquier duda, avisa!

Al turrón

**Comment by VictoriaDiro** [comment]
¡Hola Carlos! 

Ya he solucionado todas las Issues, espero que esté todo correcto.

¡Gracias y un saludo!

**Comment by oneeyedman** [comment]
Buen trabajo, @VictoriaDiro. 

Solo mira los proptypes de Pokelist, al que solo pasas 1 prop! Ajusta eso y lo damos por cerrado.

**Comment by VictoriaDiro** [comment]
Yay! Ya está hecho, me ha venido genial porque he comprendido mejor este tema solo arreglando el error. 

Gracias Carlos!
